### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by mtrojnar** [gdiepen/python_plugin_example#1]
Thank you very much for the very useful blog post and for sharing this example code.  This repository is hopefully intended to be used by other project, which requires a license.  Missing license is interpreted in most jurisdictions as "no permission to use" rather than "no restrictions".  A permissive (preferably Public Domain) license would be great.

**Comment by gdiepen** [comment]
Hi,

just added the license. Assuming MIT license is permissive enough ;)

**Comment by mtrojnar** [comment]
Yes, it is.  Thank you very much.
